OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = pimoroni_trackball
POINTING_DEVICE_DRIVER = analog_joystick
MOUSEKEY_ENABLE = yes
#Save space
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_SUPPORTED = no
